#!/usr/bin/env python
"""Run ARandR GUI"""

import sys
import gettext

# monkey patch gettext for local execution

if sys.argv[0].startswith('./'):
    old_find = gettext.find

    def find_wrapper(domain, localedir=None, languages=None, all=False):
        """Catch finds for arandr and redirect them to local files"""
        if domain == 'arandr':
            result = old_find(domain, './build/locale', languages, all)
            if result:
                return result
        return old_find(domain, localedir, languages, all)

    gettext.find = find_wrapper

# defer importing and thus loading locales until monkey patching is done

from screenlayout.gui import main
main()
